### ISSUE TITLE
关于增加更多应用以适配更多设备使用

### ISSUE THREAD

**Issue by Logic-Accepted** [YoungToday/youngtoday.github.io#1]
有的平板上没有无限宝 天天单词 wps或是注册微乐系统应用无法卸载
建议增加更多应用以适配更多设备
如org.geogebra

**Comment by Logic-Accepted** [comment]
*被注册为系统应用

**Comment by YoungToday** [comment]
自己写卡刷（

**Comment by YoungToday** [comment]
你从哪里找到这个项目的

**Comment by Logic-Accepted** [comment]
群友发的
自己写卡刷是指什么可以详细讲讲嘛 我这里rec进不去sd卡被禁用了 而且既然有360加固想必改了包名也没法用吧
